In [0]:
import numpy as np

In [0]:
x=np.array(10)
x


array(10)

In [0]:
x.shape

()

In [0]:
x.ndim


0

In [0]:
x.dtype

dtype('int64')

In [0]:
# vector 1D tensors
x=np.array([4,2,5,9])
x

array([4, 2, 5, 9])

In [0]:
x.shape

(4,)

In [0]:
x.ndim

1

In [0]:
x.dtype

dtype('int64')

In [0]:
#Matrix (2D tensors)
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
x.shape

(3, 3)

In [0]:
x.ndim

2

In [0]:
x.dtype

dtype('int64')

In [0]:
#3D Tensor
x=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]] ] )
x


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [0]:
x.shape

(3, 3, 3)

In [0]:
x.ndim

3

In [0]:
x.dtype

dtype('int64')

In [0]:
# tensor in MNIST dataset
from __future__ import absolute_import, division, print_function, unicode_literals
#install Tensorflow
!pip install tensorflow==2.0.0-beta1
import tensorflow as tf

     |████████████████████████████████| 87.9MB 70kB/s 
     |████████████████████████████████| 3.1MB 46.3MB/s 
     |████████████████████████████████| 501kB 53.1MB/s 
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [0]:
#load the MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test,y_test)= mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [0]:
print("Attributes of training data tensor")
print("==================================")
print("Number of axes in tensor = %d"%x_train.ndim)
print("Shape of a tensor:", x_train.shape)
print("Data type of tensor elements: %s"%x_train.dtype)

Attributes of training data tensor
Number of axes in tensor = 3
Shape of a tensor: (60000, 28, 28)
Data type of tensor elements: uint8


In [0]:
print("Attributes of training data tensor")
print("==================================")
print("Number of axes in tensor = %d"%y_train.ndim)
print("Shape of a tensor:", y_train.shape)
print("Data type of tensor elements: %s"%y_train.dtype)

Attributes of training data tensor
Number of axes in tensor = 1
Shape of a tensor: (60000,)
Data type of tensor elements: uint8


In [0]:
print("Attributes of training data tensor")
print("==================================")
print("Number of axes in tensor = %d"%x_test.ndim)
print("Shape of a tensor:", x_test.shape)
print("Data type of tensor elements: %s"%x_test.dtype)

Attributes of training data tensor
Number of axes in tensor = 3
Shape of a tensor: (10000, 28, 28)
Data type of tensor elements: uint8


In [0]:
print("Attributes of training data tensor")
print("==================================")
print("Number of axes in tensor = %d"%y_test.ndim)
print("Shape of a tensor:", y_test.shape)
print("Data type of tensor elements: %s"%y_test.dtype)

Attributes of training data tensor
Number of axes in tensor = 1
Shape of a tensor: (10000,)
Data type of tensor elements: uint8
